### ISSUE TITLE
关于Hugging Face Hub连接超时

### ISSUE THREAD

**Issue by chaoying0115** [hisfog/SfMNeXt-Impl#24]
作者您好，在运行python train.py ./args_files/args_res50_kitti_192x640_train.txt时，会报错Hugging Face Hub连接超时错误，请问这该如何解决。或者我能否手动下载模型权重文件，然后将其放置在脚本期望的位置？具体文件名称和位置能否请您告知一下。
错误情况如下：
(/data/ccy/env/SfMNeXt) ccy@kxB1:/data/ccy/project/SfMNeXt-Impl-main$ python train.py ./args_files/args_res50_kitti_192x640_train.txt
/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f14bbdeda90>, 'Connection to huggingface.co timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/convnext_large.fb_in22k_ft_in1k/resolve/main/pytorch_model.bin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f14bbdeda90>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1247, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1624, in get_hf_file_metadata
    r = _request_wrapper(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 402, in _request_wrapper
    response = _request_wrapper(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 425, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/convnext_large.fb_in22k_ft_in1k/resolve/main/pytorch_model.bin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f14bbdeda90>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: ecf9a333-7b8b-4830-bc46-02241ea337ff)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/ccy/project/SfMNeXt-Impl-main/train.py", line 22, in <module>
    trainer = Trainer(opts)
  File "/data/ccy/project/SfMNeXt-Impl-main/trainer.py", line 64, in __init__
    self.models["encoder"] = networks.Unet(pretrained=(not self.opt.load_pretrained_model), backbone=self.opt.backbone, in_channels=3, num_classes=self.opt.model_dim, decoder_channels=self.opt.dec_channels)
  File "/data/ccy/project/SfMNeXt-Impl-main/networks/Unet.py", line 114, in __init__
    encoder = create_model(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/timm/models/_factory.py", line 117, in create_model
    model = create_fn(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/timm/models/convnext.py", line 986, in convnext_large
    model = _create_convnext('convnext_large', pretrained=pretrained, **dict(model_args, **kwargs))
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/timm/models/convnext.py", line 486, in _create_convnext
    model = build_model_with_cfg(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/timm/models/_builder.py", line 397, in build_model_with_cfg
    load_pretrained(
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/timm/models/_builder.py", line 190, in load_pretrained
    state_dict = load_state_dict_from_hf(pretrained_loc)
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/timm/models/_hub.py", line 188, in load_state_dict_from_hf
    cached_file = hf_hub_download(hf_model_id, filename=filename, revision=hf_revision)
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/ccy/env/SfMNeXt/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1377, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
期待得到您的回复 谢谢~

**Comment by hisfog** [comment]
权重文件会默认下载到~/.cache/torch/hub/checkpoints目录下，可以手动下载权重

**Comment by chaoying0115** [comment]
你好 请问可以提供下应下载权重文件网址、名称么？在文件中没有准确找到相应的连接，麻烦了，谢谢~
